---
- name: Install required system packages
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: true
  become: true

- name: Add Docker’s official GPG key
  ansible.builtin.shell: |
    set -o pipefail
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
  args:
    executable: /bin/bash
    creates: /etc/apt/keyrings/docker.gpg
  become: true

- name: Set up the Docker repository
  ansible.builtin.copy:
    content: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    dest: /etc/apt/sources.list.d/docker.list
    mode: '0644'
  become: true

- name: Update apt package index
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Install Docker Engine and containerd
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  become: true

- name: Add user to docker group
  ansible.builtin.user:
    name: '{{ ansible_user }}'
    groups: docker
    append: true
  become: true

- name: Enable and start Docker
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started
  become: true

- name: Verify Docker is installed
  ansible.builtin.command: docker --version
  changed_when: false
  register: docker_version

- name: Print Docker version
  ansible.builtin.debug:
    msg: 'Docker version: {{ docker_version.stdout }}'
