---
- name: Deploy cengine-api
  hosts: caremate-server
  vars:
    service_name: cengine-api
  roles:
    - role: git-puller
      repo: 'git@github.com:nguyen2v/{{ service_name }}.git'
      dest: '{{ project_name }}/{{ service_name }}'

    - role: caremate-sub-project-builder
      sub_project_name: '{{ service_name }}'
