---
- name: Setup caremate project source code
  hosts: caremate-server
  roles:
    - role: git-puller
      repo: 'git@github.com:nguyen2v/{{ project_name }}.git'
      dest: '{{ project_name }}'

    - env-helper
